### ISSUE TITLE
add readme file for ORVC

### ISSUE THREAD

**Issue by Lusbert** [poiqazwsx/RVC-Notebooks#1]
[readme.md](https://github.com/poiqazwsx/RVC-Notebooks/files/13877713/readme.md)
add this for the Open in Collab button @poiqazwsx

**Comment by poiqazwsx** [comment]
pull requests exist 😭

**Comment by poiqazwsx** [comment]
done

**Comment by Lusbert** [comment]
> pull requests exist 😭

too lazy uwu
